services:
  postgres:
    image: 'postgres:15'
    container_name: remitly-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - '5432:5432'
    networks:
      - backend
  redis:
    image: 'redis:7.4.2'
    container_name: remitly-redis
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    networks:
      - backend
  app:
    container_name: remitly-task-app
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_URL: ${REDIS_URL}
    ports:
      - '8080:8080'
    networks:
      - backend

volumes:
  cache:
    driver: local
networks:
  backend:
    driver: bridge