spring:
  application:
    name: remitly-task-app
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    name: ${DB_NAME}
    url: ${DB_URL}
  data:
    redis:
      url: ${REDIS_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    cache-names: redis-cache
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 10s